### ISSUE TITLE
Bug : Visual Glitch

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/SantasMagicNight#182] opened 2020-11-11 11:37 UTC
Ref to the image provided, When santa is stuck in the loop and you click on the gingerbread man standing besides it, the red direction option keeps blinking for a split second. This is cause of how it is coded however it looks glitchy to a third person when that red option keeps blinking/ flashing.
![image](https://user-images.githubusercontent.com/56066524/98807214-535c5900-2440-11eb-9af5-7438d431bf10.png)

**Comment by mustucontractor** [comment] 2020-11-11 11:40
This level is overall buggy since you cant select when you want to go and have to keep spamming click when santa in stuck in a loop

**Comment by SilasReinagel** [comment] 2020-11-11 21:55
Duplicate of #164.

**Closed by SilasReinagel** 2020-11-11 21:55 UTC
